### ISSUE TITLE
Notes not being shown when Dark Theme active

### ISSUE THREAD

**Issue by Neolize** [xatupal/KeeTheme#10]
Hey,
First of all: thank you very much for creating this plugin. I am someone who wants night mode for EVERYTHING, so I was so grateful to see someone creating a theme plugin for KeePass2. :)

I currently have an issue with the "Notes" in my entries. 

The Notes are shown in dark theme and in light theme but I can't seem to edit or see them whenever I open the entry. (I added screenshots)
![Screenshot1](https://user-images.githubusercontent.com/52655835/60799952-799b2600-a174-11e9-91a7-0eda7402ab42.JPG)
This is way I see my entry in DarkMode.
![Screenshot2](https://user-images.githubusercontent.com/52655835/60800004-9a637b80-a174-11e9-8ec3-df74622ed42c.JPG)
And here is the way I see it in LightMode. 

You can clearly see that I added notes to the entry, but when I open the entry up:
![Screenshot3](https://user-images.githubusercontent.com/52655835/60800073-c8e15680-a174-11e9-8488-f082a821ca96.JPG)
The notes seem to have vanished and I can't click in the Notes box. 

But in LightMode it works again:
![Screenshot4](https://user-images.githubusercontent.com/52655835/60800151-f3cbaa80-a174-11e9-9b30-50680551be69.JPG)

Sorry if I forgot anything important, I've just created this account and I am new to GitHub. 

Specs: Windows 10 Pro 64bit (latest update)
KeePass 2.42.1 
KeeTheme V.0.5.4.0

**Comment by solhuebner** [comment]
Same issue here: Windows 10 Ent x64 / KeePass 2.42.1 / KeeTheme 0.5.4

**Comment by xatupal** [comment]
Thanks for info! I'm glad you like my plugin. Problem fixed.
