### ISSUE TITLE
Change Ctrl+T as theme changer hotkey

### ISSUE THREAD

**Issue by theking2** [xatupal/KeeTheme#101]
As the Ctrl + T key is reserved for copying the TOTP it should not be used for changing the theme.
![image](https://github.com/xatupal/KeeTheme/assets/1612152/2f974373-639d-4246-90ba-addbc1c79954)

Please use use something else as default. Alt+T ?

**Comment by xatupal** [comment]
Hey! You can change KeeTheme hot-key in options:
![obraz](https://github.com/xatupal/KeeTheme/assets/22529861/8b088e6e-ee1c-4768-8192-bd9ff17dd61c)

**Comment by theking2** [comment]
thanks . cool

**Comment by sidlr** [comment]
I have the same issue and I don't see the KeeTheme entry in the options. I'm running KeePass 2.56 with Mono on an Ubuntu 22.04.3 LTS system.
Would it be possible to add the configuration for the hot key manually to the KeePass.config.xml file or how is it stored?
