### ISSUE TITLE
Question: KeeTheme.dll

### ISSUE THREAD

**Issue by theking2** [xatupal/KeeTheme#107]
I have a question. What is the reason of the .dll file? Without it and only plgx in the plugins folder keepass seems to work fine in dark mode.

**Comment by xatupal** [comment]
It's described in detail here: https://keepass.info/help/v2_dev/plg_index.html, PLGX files section.
In short: only one file is required to make it work. PLGX offers greater compatibility, DLL provides greater security.

**Comment by theking2** [comment]
Got it, Thanks!
