### ISSUE TITLE
Design bug

### ISSUE THREAD

**Issue by f3lixdev** [xatupal/KeeTheme#12]
![grafik](https://user-images.githubusercontent.com/52625423/62217963-d5d81b00-b3ab-11e9-8371-f59a76fa5eab.png)

While using the KPEnhancedEntryView plugin, the dark theme leaves white fields.
If I switch back to normal (white) mode, the attachment field is still black.

**Comment by f3lixdev** [comment]
Since the last update some files are in dark mode, but other still use the normal mode.
![grafik](https://user-images.githubusercontent.com/52625423/62604209-d3b81400-b8f7-11e9-9838-13073895c223.png)

**Comment by f3lixdev** [comment]
The attachment area is still in dark mode
![grafik](https://user-images.githubusercontent.com/52625423/62604403-4c1ed500-b8f8-11e9-9dc8-0cc5addee326.png)

**Comment by xatupal** [comment]
Thanks for info, I'll check it.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
can confirm the issue described.

![image](https://user-images.githubusercontent.com/46166740/64081588-89159600-cd03-11e9-88ed-5d0c5145b22c.png)
