### ISSUE TITLE
Attachment Viewer needs some fixing

### ISSUE THREAD

**Issue by 24Marques** [xatupal/KeeTheme#13]
Hi, just noticed that the attachment viewer for rtf and txt files looks diferent with the dark theme on, in terms of size of the box.
Also the text color function is not working for rtf files with dark theme.
Here are some examples:

<details>
  <summary>RTF examples (Click to expand)</summary>
  
![image](https://user-images.githubusercontent.com/52248535/62767910-92596d00-ba8d-11e9-824e-893749b60493.png)
![image](https://user-images.githubusercontent.com/52248535/62767898-8a99c880-ba8d-11e9-9e97-2424543ff9ea.png)
</details>

<details>
  <summary>TXT examples (Click to expand)</summary>
  
![image](https://user-images.githubusercontent.com/52248535/62767944-a7ce9700-ba8d-11e9-843b-5c6e2f4c4995.png)
![image](https://user-images.githubusercontent.com/52248535/62767951-a9985a80-ba8d-11e9-8b27-1278f9ee7bcb.png)
</details>

Thanks for all the work you're doing! Great stuff.

**Comment by xatupal** [comment]
Thanks for info, I'll check it.
