### ISSUE TITLE
Theme not remembered after restart

### ISSUE THREAD

**Issue by ForgeSource** [xatupal/KeeTheme#18]
Using V0.6.2, when I restart KeyPass, it does not remember that I had a theme selected, so I have to reselect it (with <CTRL>-T or through the menu) after every restart.

**Comment by xatupal** [comment]
Thanks for info. I can not reproduce this behavior. Are there any other conditions that must be met?

**Comment by f3lixdev** [comment]
I'm also using v0.6.2 and KeeTheme works fine.

**Comment by ForgeSource** [comment]
I'm running KeePass 2.43 under Windows 10. It starts without a theme. I apply my theme using either CTRL+T or the Menu and it is applied correctly. I then use File > Exit to exit KeePass. When I restart it, it is not showing my theme (and nor was the authentication window which is presented when you start KeePass). This behaviour didn't happen with previous versions (which kept their themes).

I have both the .DLL and the .PLGX files in my Plugins directory.

Happy to share my KeeTheme.ini file or provide any other information which may help.

**Comment by ForgeSource** [comment]
Just updating to note that the issue is still present with V0.6.3.

**Comment by xatupal** [comment]
I still can't reproduce this behavior. Do you have any other plugins installed?

**Comment by ForgeSource** [comment]
Thanks. I did have two other plugins (KeyPassRPC and Yet Another Favicon Downloader) installed, but I have just tried removing them both from my Pluging directory and it made no difference. I've also tried using just the DLL or just the PLGX for KeeTheme (with nothing else in the Plugins folder), but again it didn't resolve the issue. Is it possible that there is something in my KEETHEME.INI file which is causing this?

**Comment by xatupal** [comment]
Unlikely, but you can just remove your `KeeTheme.ini` and check.

**Comment by ForgeSource** [comment]
Thanks. I've updated to V0.6.4, and removed my KeeTheme.ini file but I'm still having the same issue (i.e. I start KeePass and apply the default _Dark Theme_ theme. But once I exit KeePass and restart it, the display is back to the default.)

**Comment by stonecrusher** [comment]
I have the same issue.
Looking at the switch at Extras --> [MyThemeName] it is checked, but not applied. If I uncheck it, the theme is applied.
![2019-12-18_10](https://user-images.githubusercontent.com/1388389/71074378-72942d00-2182-11ea-8642-7d1f85fd771b.png)
![2019-12-18_10-2](https://user-images.githubusercontent.com/1388389/71074379-72942d00-2182-11ea-860c-e12d8fbe8c24.png)
Win10x64 (1909)
KeePass 2.43
KeeTheme 0.6.4.0

**Comment by ForgeSource** [comment]
If it helps (1) I see the same behaviour as stonecrusher (theme is only applied when it's unchecked), and (2) I have the same issue on both my desktop and my laptop, so it's not just machine specific.

**Comment by xatupal** [comment]
Thanks for info. I've got one more idea.

**Comment by stonecrusher** [comment]
First tests: Seems to work now, thank you!
p.s.: Another thing that came to my mind is interference with the option to start KP minimized (activated for me).

**Comment by ForgeSource** [comment]
And fixed for me here also. Thank you very much!
