### ISSUE TITLE
not compatible with the version 2.43

### ISSUE THREAD

**Issue by yingw** [xatupal/KeeTheme#19]
![image](https://user-images.githubusercontent.com/1177503/67136782-e3d86200-f25d-11e9-9a76-dac9839b3b56.png)

**Comment by xatupal** [comment]
Thanks for info. I can not reproduce this behavior. Are there any other conditions that must be met?

**Comment by yingw** [comment]
hi , @xatupal  thanks for your reply, Nothing special, using Ubuntu 18.04.4, dark-Mojave-theme, I re-tested with many env settings, such as themes, languages, and re-installed the keepass, just left this one plugin, yet the issue still ( show the warning messange , and no "Tool->DarkTheme" menu.)
![image](https://user-images.githubusercontent.com/1177503/67434962-c4568600-f61d-11e9-8879-4f398151c1f6.png)
![image](https://user-images.githubusercontent.com/1177503/67435168-257e5980-f61e-11e9-9d4b-3dea0bf17be4.png)

![image](https://user-images.githubusercontent.com/1177503/67435194-3202b200-f61e-11e9-92a7-302e1e1cd104.png)

Anything useful?

**Comment by deathtrip** [comment]
does this plugin even officially support linux?

**Comment by xatupal** [comment]
Officially not. Given the number of hacks that were used to make it work on Windows I was surprised that it worked on Linux. Nevertheless I am able to run it (KeePass.plgx) on Ubuntu 18.04 + Mono 4.6.2 (mono-complete package).

![obraz](https://user-images.githubusercontent.com/22529861/70420069-1c7b0780-1a67-11ea-92c5-75e157ef9d21.png)

**Comment by xatupal** [comment]
@yingw could you confirm that you have Mono 4.6.2 (mono-complete package)?

**Comment by LaurentDumont** [comment]
So I'm running the Linux community made Keepass2  version. The current Keepass version is 2.41. I've tried downgraded the KeeTheme to a version where Windows2.41 is supported but it doesn't seem to work.

![image](https://user-images.githubusercontent.com/8936473/71560184-79e5f100-2a34-11ea-8ad1-99083ab5ec40.png)

I'm pretty sure I'm falling into unsupported territory but I'm just curious if anyone was able to make this work!

Thanks

**Comment by xatupal** [comment]
@LaurentDumont what version of Mono do you have? I'm pretty sure that the problem lies in Mono, because under the hood plgx is just packed source code that have to be compiled by KeePass to make it work.

**Comment by Xaardas** [comment]
Hello. I had the Same Problem with my Keepass Version 2.43 under Windows 10.
I am using different other plugins, but the error occured regardless of whether i used them or not. Maybe this error Message can help?

<img width="413" alt="1" src="https://user-images.githubusercontent.com/59469854/71715303-45e24580-2e11-11ea-80f8-6fabbde55dc8.png">

Anyways. Downloading a fresh copy of keepass 2.43 did the trick for me. But I have no clue why and how that fixed the Problem.

**Comment by xatupal** [comment]
@Xaardas thx! There was an invalid framework version in resources file.

**Comment by Xaardas** [comment]
@xatupal No Problem, i am glad i could help.
