### ISSUE TITLE
dark mode .ini file

### ISSUE THREAD

**Issue by lluke777** [xatupal/KeeTheme#20]
Hi. Great Plugin
Is there a filled version of file below with default settings for dark mode?
https://github.com/xatupal/KeeTheme/blob/master/themes/KeeTheme.ini
I would like to tweak a little bit dark theme so with default values of dark mode in .ini file it would be faster.

**Comment by f3lixdev** [comment]
In general is it possible to create a "gallery" with some themes on github?

**Comment by xatupal** [comment]
Thx @lluke777, here you can download a file with default settings - [DarkTheme.ini](https://github.com/xatupal/KeeTheme/blob/master/KeeTheme/Resources/DarkTheme.ini).

@f3lixdev it is possible, but there is only one other theme that I'm aware of - [DarkenKP](https://github.com/BradyThe/DarkenKP).
