### ISSUE TITLE
Dark theme is "masking" '&' and underling the next character instead

### ISSUE THREAD

**Issue by dimalantak** [xatupal/KeeTheme#21]
When using KeeTheme with KeePass, passwords that have the '&' character do not show up on the password preview screen and instead underline the next character.

![image](https://user-images.githubusercontent.com/18562864/68998151-5b9cab00-0863-11ea-88ac-b8ffb9173134.png)

![image](https://user-images.githubusercontent.com/18562864/68998158-68210380-0863-11ea-89b7-9e4b6eb2fa69.png)

If I use CTRL + T and revert to the light theme the issue no longer happens.

**Comment by xatupal** [comment]
Thanks for info. I'll fix it.
