### ISSUE TITLE
Designbug in Treeview

### ISSUE THREAD

**Issue by felixoswald** [xatupal/KeeTheme#26]
![image](https://user-images.githubusercontent.com/52625423/73594379-3ccabe00-450e-11ea-9116-38ce2e5db2b8.png)
With enabled default dark mode the size of the background boxes are different.
Note:
- Only on selected items
- Only on elements with " & "

**Comment by xatupal** [comment]
Thanks for info. I'll fix it.

**Comment by xatupal** [comment]
Unfortunately I was not able to reproduce this behavior.
![obraz](https://user-images.githubusercontent.com/22529861/74373052-0594c080-4ddc-11ea-90b4-bcdc7a8ce756.png)
I've also tried with bigger and different fonts:
![obraz](https://user-images.githubusercontent.com/22529861/74373291-750ab000-4ddc-11ea-95ca-cebb8290ee8f.png)
Everything looks fine in both cases.

What kind of font do you use?

**Comment by felixoswald** [comment]
I'm using Calibri Bold 12pt as list font.

**Comment by felixoswald** [comment]
"&" is automatic replaced with " _ " (underscore) by Keepass.
The bug occurs with groups with "&".
