### ISSUE TITLE
Dark shadow behind black text in password quality field

### ISSUE THREAD

**Issue by fanchyfanch** [xatupal/KeeTheme#27]
In the entry dialog, there is some kind of dark shadow just behind the text indicating password strength which annoys reading (as you can see on the screenshot).

![Image 1](https://user-images.githubusercontent.com/3300245/74228760-041ea780-4cb9-11ea-9c97-51514a1d560d.png)

![Image 3](https://user-images.githubusercontent.com/3300245/74230481-bdcf4580-4cc4-11ea-8daf-e7665fea2034.png)

Would it be possible to remove it and/or to set the text to be black to increase contrast and improve reading confort?

Thanks a lot for your great plugin which let me reduce my eyes strain with one of my favorite and daily application: KeePass. What a good idea you got there.

Fanch

**Comment by xatupal** [comment]
I'm glad you like the plugin. I've changed the text color and the shadow has disappeared.
