### ISSUE TITLE
attachements arrow 'open with' disappearing with dark theme

### ISSUE THREAD

**Issue by libix** [xatupal/KeeTheme#30]
hi, 
the little arrow that brings up the menu to open an attachment in external/internal viewer is not working and not showing with the theme activated (i'm using latest version of keetheme (0.6.9) and keepass 2.44)

without theme : 
![KeePass_Gc159vwdiL](https://user-images.githubusercontent.com/11389241/79567096-e5230400-80b3-11ea-8cb7-61b347ad07eb.png)

with theme : (and the attachment is selected, so the arrow should be there)
![image](https://user-images.githubusercontent.com/11389241/79567203-113e8500-80b4-11ea-84dc-e4e0976c1c31.png)

maybe i'm doing something wrong but i think it's a bug
thx

**Comment by xatupal** [comment]
Hi, you're right. Unfortunately it's not easy to fix. I'll see what I can do.
