### ISSUE TITLE
Font Color & Size Make Fonts Hard to Read

### ISSUE THREAD

**Issue by koolx** [xatupal/KeeTheme#31]
The font is grey and hardly readable. Please color them white and enlarge it.

**Comment by aFooBar** [comment]
Why all the Dark themes give the impression the applications are bub off/washed out :/
Having a more blackished theme would definitively increase readability

**Comment by bendover22** [comment]
I haven't installed the dark KeeTheme yet, but if the screens are a good representation, I have to agree.  Some of the disabled fonts are barely visible.
I have some moderate vision issues & I need fairly good contrast.  

Though disabled text / options are supposed to be less bright, you still need to be able to read them.  Sometimes things are disabled when they shouldn't be.  Or you may want to find how to activate some disabled options.

**Comment by madmax2** [comment]
@xatupal just look at your own windows explorer in Windows 10
when you enable dark theme..
it is using white text on a dark background..

Your dark theme is pretty useless since it is very hard to read the text.
Please fix this.

Whichever guideline/s you got this idea from is wrong or outdated.

**Comment by xatupal** [comment]
You were right. Contrast ratio between background and text was too low. I've increased it to the proper level. 
Old ratio: [3.81](https://contrast-ratio.com/#rgb%28167%2C168%2C167%29-on-%2345494A), new ratio: [7.09](https://contrast-ratio.com/#rgb%28227%2C227%2C227%29-on-%2345494A)

@Darthagnon thanks for the great theme!
