### ISSUE TITLE
When i deactivate dark theme, a large part of GUI remains dark grey

### ISSUE THREAD

**Issue by timBorelle** [xatupal/KeeTheme#33]
I use your KeeTheme plugin

Standard interface :
![Keepass1_standard_interface](https://user-images.githubusercontent.com/22890257/85204317-fc7ca880-b313-11ea-99cb-ab921d2e8cfb.PNG)

When i activate dark theme, GUI swith to dark theme :
![Keepass2_darkTheme_activated](https://user-images.githubusercontent.com/22890257/85204320-fdadd580-b313-11ea-8b87-1367cea9d868.PNG)

But when i deactivate dark theme, a big part of Keepass GUI remains in dark theme
![Keepass3_darkTheme_deactivated](https://user-images.githubusercontent.com/22890257/85204323-fe466c00-b313-11ea-9aae-e1dd12a591a6.PNG)

**Comment by TBugReporter** [comment]
Still seeing this with v0.9.1.
![Screenshot](https://user-images.githubusercontent.com/16196686/118603723-dba02a00-b7e6-11eb-9dc2-a55c46cc1915.png)

**Comment by TBugReporter** [comment]
Why is this issue closed?
