### ISSUE TITLE
Dark Theme also hides custom background colors

### ISSUE THREAD

**Issue by Retrospector** [xatupal/KeeTheme#34]
Hi,
I'm using custom background colours to highlight certain entries in my database. I was glad when I found this Plugin, since KeePass didn't look great on my Linux Mint 20 System.
So maybe this is just an incompatibility with running KeePass on Linux, but the Dark theme also hides all my custom background colours. I have added a screenshot comparing the regular look and the look with the dark theme enabled:
![KeeTheme_CustomBackround](https://user-images.githubusercontent.com/2715287/86367827-bb25ba80-bc7c-11ea-8cef-13303a9e65dd.png)

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
it is not just an incompatibility with running KeePass on Linux.
