### ISSUE TITLE
KeeTheme does not work under KeePass 2.46

### ISSUE THREAD

**Issue by Xaardas** [xatupal/KeeTheme#37]
Like the Title. Unfortunately KeeTheme does not work anymore with the new KeePass version. Is there any quick solution or can we expect something in the near future?

Best Regards
Xaar

**Comment by phpony** [comment]
I'm using it with KeePass 2.46 right now. What exact problem do you have?

**Comment by Xaardas** [comment]
Hello,

 

when I want to start KeePass I am getting the Message, that the KeeTheme.dll Plugin is not compatible with KeePass 2.46.

I am attaching a picture of the error message to this mail. I hope this helps.

 

 

Best Regards

 

Stefan Gerstberger

 

 

 

Von: Volkov Maksim <notifications@github.com> 
Gesendet: Samstag, 24. Oktober 2020 19:46
An: xatupal/KeeTheme <KeeTheme@noreply.github.com>
Cc: Xaardas <stefan.gerstberger@2guygames.com>; Author <author@noreply.github.com>
Betreff: Re: [xatupal/KeeTheme] KeeTheme does not work under KeePass 2.46 (#37)

 

I'm using it with KeePass 2.46 right now. What exact problem do you have?

**Comment by phpony** [comment]
Have you tried downloading the lastest release of plugin? 

https://github.com/xatupal/KeeTheme/releases/tag/v0.6.10

Just downloaded lastest keepass and latest keetheme, and them work together...

**Comment by Xaardas** [comment]
Okay this is odd. I Downloaded version 0.6.10 and tried it with 2.46 and it worked. Jet when I look the KeeTheme Version up in 2.45 it is also Version 0.6.10.

 

Anyways it works now somehow. I have no idea what went wrong…or right in this case.

 

Von: Volkov Maksim <notifications@github.com> 
Gesendet: Sonntag, 25. Oktober 2020 21:17
An: xatupal/KeeTheme <KeeTheme@noreply.github.com>
Cc: Xaardas <stefan.gerstberger@2guygames.com>; Author <author@noreply.github.com>
Betreff: Re: [xatupal/KeeTheme] KeeTheme does not work under KeePass 2.46 (#37)

 

Have you tried downloading the lastest release of plugin?

https://github.com/xatupal/KeeTheme/releases/tag/v0.6.10

Just downloaded lastest keepass and latest keetheme, and them work together...

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> Anyways it works now somehow.

Then you might close this issue?

**Comment by Xaardas** [comment]
Oh Sorry,

 

yes I will do that.

 

Have a nice week.

 

Von: Bernd Eichelberger <notifications@github.com> 
Gesendet: Samstag, 5. Dezember 2020 13:24
An: xatupal/KeeTheme <KeeTheme@noreply.github.com>
Cc: Xaardas <stefan.gerstberger@2guygames.com>; Author <author@noreply.github.com>
Betreff: Re: [xatupal/KeeTheme] KeeTheme does not work under KeePass 2.46 (#37)

 

Anyways it works now somehow.

Then you might close this issue?
