### ISSUE TITLE
Color selector descriptions

### ISSUE THREAD

**Issue by user8446** [xatupal/KeeTheme#4]
I want to create a theme but there are over 100 different selectors of buttons, selectors, gradients, etc. Is there an easy way of knowing what each is?

**Comment by xatupal** [comment]
Yes, there is. Each type of control has its own section in the ini file.
For example, if you want to customize buttons look for [Button] section.
If you want to customize main list view then look for [ListView] section
etc.

The only control with greater customization abilities is [ToolStrip] (menu
and toolbar).
That's why there are plenty of different selectors in this section.

Looking forward to see your theme :)

Regards.


czw., 9 maj 2019 o 03:46 Glenn <notifications@github.com> napisał(a):

**Comment by user8446** [comment]
Hi,
Thanks but how do we know what each is? For example:

ColumnBorderColor 
HeaderBackColor 
HeaderForeColor
ImageMarginRevealedGradientEnd 
MenuStripGradientBegin 
MenuStripGradientEnd

How would we easily know what each of those are without changing it, then viewing the results, then go back into the template?

**Comment by BradyThe** [comment]
> How would we easily know what each of those are without changing it, then viewing the results, then go back into the template?

If I am uncertain about a particular code, I usually do exactly that. It's a little labour-intensive but very effective. Eventually you will get used to the meaning of variables.

BorderColor = Colour of Border
BackColor = Colour of Background
ForeColor = Colour of Text
MenuStripGradientBegin = Begin of MenuBar (File ... Help) Background Gradient | Gradient going from left to right | settings will be overwritten by [Control] BackColor
MenuStripGradientEnd = End of MenuBar (File ... Help) Background Gradient | settings will be overwritten by [Control] BackColor
ImageMarginRevealedGradientEnd = Haven't found where that one is applied yet, however ImageMarginGradientxxx styles the Icon space on the left in sub menus

I have been a little lazy with my style and have not completed it yet. I'll (probably) do that tomorrow and upload it. It comes with a few comments that might help you.

**Comment by xatupal** [comment]
@user8446, the plugin mostly just substitutes control colors. It does not draw them from scratch. 
So the naming follows from the control property names in the code, eg. [BackColor](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.backcolor), [ForeColor](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.forecolor).
Fortunately, as @BradyThe wrote, there are some common conventions.

As for menu and toolbar the description is here: [ToolStrip colors](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.professionalcolortable#properties).

**Comment by xatupal** [comment]
@BradyThe thanks! Your theme is the first another theme. I'll mention about it on KeePass forum.

**Comment by ForgeSource** [comment]
_MenuStripGradientBegin = Begin of MenuBar (File ... Help) Background Gradient | Gradient going from left to right | settings will be overwritten by [Control] BackColor
MenuStripGradientEnd = End of MenuBar (File ... Help) Background Gradient | settings will be overwritten by [Control] BackColor_

Is there any way to prevent this behaviour ("settings will be overwritten by [Control] BackColor")? I have BackColor set to a Dark Grey, but the menu labels ("File", "Group", "Entry", etc) are still Black and so are impossible to read on the Dark Grey background. I can't find any setting which will change the colour of the Button text :-(

**Comment by BradyThe** [comment]
> Is there any way to prevent this behaviour ("settings will be overwritten by [Control] BackColor")? I have BackColor set to a Dark Grey, but the menu labels ("File", "Group", "Entry", etc) are still Black and so are impossible to read on the Dark Grey background. I can't find any setting which will change the colour of the Button text :-(

I don't have an answer to that because I have not spent too much time on this particular problem, but menu labels are styled via
```
[Control]
ForeColor
```

**Comment by xatupal** [comment]
I was thinking about this problem and came to the conclusion that menu items should have their own settings for ForeColor and BackColor, as a result, they will not be overwritten by the Control settings. I will implement this in the next release.

@BradyThe I'll let you know if it will affect your theme.

**Comment by xatupal** [comment]
Finally, the new version is released.

@BradyThe you should add the following lines to the KeeTheme.ini:
```ini
[MenuItem]
BackColor = BackgroundColourDarkest
ForeColor = TextColour
HighlightColor = TextColour
```
Of course you can choose any colors you want :)

**Comment by ForgeSource** [comment]
Thank you VERY much for providing this functionality!
