### ISSUE TITLE
White Background after locking Database

### ISSUE THREAD

**Issue by jaspervf** [xatupal/KeeTheme#41]
When using the default Dark Theme, the workspace background is white after locking the workspace.

The background is correctly colored on startup and when opening a database, but the bug occurs when manually locking the workspace (e.g. via <kbd>Ctrl</kbd> + <kbd>L</kbd>). However it switches back to dark after entering the password.

It looks like this:

![grafik](https://user-images.githubusercontent.com/74309593/110257988-a4203080-7fa0-11eb-8b1b-1abffdc43fed.png)

**Comment by yderi** [comment]
Hello all 

I also confirm the issue. It lights into your eyes when you switch to unlock, especially if you set all environments to use a dark theme and works in a dark room.

Best regards
