### ISSUE TITLE
Resized windows disappear [KeeResize]

### ISSUE THREAD

**Issue by MageNext** [xatupal/KeeTheme#43]
When using KeeResize extension, in dark mode the resized windows disappear. Add entry or edit entry resizing does it.

**Comment by xatupal** [comment]
I've downloaded KeeResize plugin and couldn't reproduce the problem.
I can resize add/edit entry window and nothing disappears.
Are there any other conditions that must be met?

**Comment by MageNext** [comment]
Yes, there is after trying without KeeTheme (dark mode). It is conflicting,
it might be on their end or not, not sure.

**Comment by xatupal** [comment]
Unfortunately, still no luck. 
Even when KeeTheme is disabled I can resize add/edit entry window and nothing disappears.
Maybe some other plugin causes problem?

**Comment by MageNext** [comment]
100% KeeTheme with KeeResize. When KeeTheme is disabled KeeResize works properly. Doesn't mean it is KeeTheme, it could be KeeResize, but both extensions on github don't get the proper response from the authors.

**Comment by xatupal** [comment]
I assume the problem was the same as #53. If not I will re-open this issue.
