### ISSUE TITLE
InvalidCastException after enabling Auto-sync with Windows 10 theme

### ISSUE THREAD

**Issue by fwmone** [xatupal/KeeTheme#47]
Tested with KeePass 2.48.1 on Windows 10 Home (German language) on Light Theme. 
When enabling Auto-sync with Windows 10 theme in options Tools -> Options... -> KeeTheme, I get an InvalidCastException error when I have Windows Light Theme enabled. This is shown on every start of KeePass, too, leading to the plugin being disabled by KeePass:

![grafik](https://user-images.githubusercontent.com/58838405/118400157-ba153600-b660-11eb-8758-9b7dc6b7a86c.png)

It works, when I switch to Windows 10 Dark Theme but stops working again when switching to Light Theme (I use Light Theme by day and Dark Theme by night).

**Comment by xatupal** [comment]
Thanks for info. Fixed.
