### ISSUE TITLE
DarkTheme.ini

### ISSUE THREAD

**Issue by Gankaku** [xatupal/KeeTheme#49]
Hello!

I'm so sorry if this is not the correct place to post this. I found the correct place an hour ago but for the life of me I cannot find it again!

I am having difficulty with DarkTheme.ini. I download the .ini template file [here](https://github.com/xatupal/KeeTheme/blob/master/themes/KeeTheme.ini). Then I made a few changes to the colors on the tree view. (at least I believe it's where I'm supposed to make them.) I've left everything else alone. I put the DarkTheme.ini into the Plugins folder for KeePass. I don't see any change whatsoever. 

Is there something else I need to be doing? Messing with it for over an hour lol

Thanks! I appreciate all the regular updates. This is one of my most regularly used apps and the dark theme is so wonderful.

**Comment by xatupal** [comment]
Hello Gankaku! I'm glad you like the plugin!

The file in the Plugins folder should be named _KeeTheme.ini_ and then the plugin will load it.
I would recommend downloading [DarkTheme.ini](https://github.com/xatupal/KeeTheme/blob/master/themes/DarkTheme.ini) and modify it, so you don't have to start from the beginning.

If you still have problems with that, don't hesitate to ask.

**Comment by Gankaku** [comment]
Oh well I didn't know that! At first I thought I could name it whatever I want (I don't know why...that's silly). Then I thought I should just leave it named DarkTheme. So Okay thank you! I will do that now. I love how the original Dark Theme looks by itself, but it's always fun with a little personalization. Also I saw a place where I could color links? I want to try that too, because just a couple of days ago, someone and I were talking about it and they said they wanted the links to have different colors. If it works, I can tell him how.

**Comment by xatupal** [comment]
Great that it works! Sorry for late reply. I've missed your answer.
[KeeTheme.ini](https://github.com/xatupal/KeeTheme/blob/master/themes/KeeTheme.ini) is just empty template, so unfortunately you have to change most of the color selections.
As for the color of links in the Notes area - please attach a screenshot. I'll see what I can do about them.

**Comment by xatupal** [comment]
Since version 0.10.0 you can use built-in theme editor to create your own theme.
And by the way, link color in the Notes area was also fixed.
