### ISSUE TITLE
Title bar does not switch into dark mode and stays white

### ISSUE THREAD

**Issue by theincogtion** [xatupal/KeeTheme#50]
This is also visible here:
https://github.com/xatupal/KeeTheme/blob/master/docs/KeePassDarkTheme.png
The title bar remains white.

**Comment by LordDurus** [comment]
I'm not surprised by that at all.  
Changing the title bar color in a WinForms app in Windows 10 is not trivial.

**Comment by rxpsych** [comment]
I definitely think it's related to the Window Title color selected in Windows 10. There are small programs found on-line that can help to easily change active and inactive title bar colors.

**Comment by theincogtion** [comment]
Thanks for the hint. Windows 10 has an option for this. No program needed.
Just can provide a german screenshot
![grafik](https://user-images.githubusercontent.com/10852327/122163625-bea65780-ce75-11eb-9db3-036eb9bbc0a0.png)

**Comment by xatupal** [comment]
I've done some research and I think it's easily achievable in Windows 10. I'll do it in the next release.
