### ISSUE TITLE
KeeTheme and KeeResize make comment area not writeable

### ISSUE THREAD

**Issue by ezek1el** [xatupal/KeeTheme#53]
As soon as both plugins are active the comment field in the new entry window is not clickable and you cannot add anything or read anything. Each plugin alone works just fine.

Windows 10
Keepass 2.49
KeeTheme 0.9.2.0
KeeResize 1.12.0.0

**Comment by ezek1el** [comment]
x-post keepass discussion: [https://sourceforge.net/p/keepass/discussion/329221/thread/f086511e83/](url)

**Comment by Naugrimohtar** [comment]
I have seen this as well.

**Comment by MageNext** [comment]
I have the same issue. This just recently started after either keepass or keetheme updates.

**Comment by xatupal** [comment]
Hi! I unable to reproduce the problem. Does it still occur?

My environment:
Windows 10
Keepass 2.49
KeeTheme 0.9.4.0
KeeResize 1.12.0.0

**Comment by ezek1el** [comment]
Yes it does

**Comment by MageNext** [comment]
Same here as eze1el, same environment. Note area is not editable when dark mode is enabled. I am using KeeResize as well. There is another duplicate thread created by me a year ago.

**Comment by xatupal** [comment]
Ok, I'll try to investigate it. Could you post a screenshot? Is your KeeResize registered?

**Comment by ezek1el** [comment]
Yes it is. Here is a [screenshot](https://abload.de/img/20220216205158v5jxt.jpg):

**Comment by xatupal** [comment]
What is "Kee" tab page? Do you have any other plugins installed?

**Comment by ezek1el** [comment]
That is the KeePassRPC Plugin. Here a list of the installed plugins: [KLICK](https://abload.de/img/2022-02-16_220154lhjkr.jpg)
I have tested with and without other plugins. Same result.

**Comment by xatupal** [comment]
Ok, it turned out that the problem is with the full version of KeeResize. 
Now when I can reproduce the problem I'll see if I can do something about it.

**Comment by xatupal** [comment]
As a temporary solution you can resize the Edit Entry window, because the comment is there but it is in the wrong place.
![obraz](https://user-images.githubusercontent.com/22529861/154566308-586047e8-3387-4ec0-b840-84dc7f92e310.png)

**Comment by ezek1el** [comment]
0.9.6.0 resolves the issue. Thank you!
