### ISSUE TITLE
Very light color for "Edit Auto-Type item" dialogue on Windows 10

### ISSUE THREAD

**Issue by d-Rickyy-b** [xatupal/KeeTheme#54]
Hey, thank you for this nice theme. I got a small issue with the "Edit Auto-Type item" dialogue on Windows 10. When it's set to the "default keystroke sequence" the bottom part is grey/disabled. Sadly this doesn't look good with a dark theme applied.

![grafik](https://user-images.githubusercontent.com/5798157/124335983-92404a00-db9c-11eb-9a73-279dc287792b.png)

![grafik](https://user-images.githubusercontent.com/5798157/124336039-cb78ba00-db9c-11eb-947a-9b3aa0c264f3.png)

I'd highly appreciate a fix for this :)

Cheers
Rico

**Comment by xatupal** [comment]
Thanks for info. Fixed.
