### ISSUE TITLE
KeeResize and Dark Theme are interfering with each other

### ISSUE THREAD

**Issue by MageNext** [xatupal/KeeTheme#56]
I am using KeeResize, and when I use dark theme, dialog boxes disappear. 
https://keepass.info/plugins.html#keeresize

I've contacted KeeResize, they said it is the dark theme, not their plugin. In normal light mode, it works fine.

**Comment by xatupal** [comment]
Hi! Which dialog boxes disappear? I tested KeeTheme with KeeResize and I didn't notice any problems.

My environment:
Windows 10
Keepass 2.49
KeeTheme 0.9.4.0
KeeResize 1.12.0.0

**Comment by MageNext** [comment]
My environment: 
Win10
KeePass: 2.5
KeeResize: 1.12
KeeTheme: 0.9.4

While in dark mode, it shows the Notes area fine with preview. When editing that note area in dark mode, no text is visible and it is uneditable.

**Comment by xatupal** [comment]
Still no luck. Could you post a screenshot?

**Comment by xatupal** [comment]
I assume the problem was the same as #53. If not I will re-open this issue.
