### ISSUE TITLE
First Column Bug

### ISSUE THREAD

**Issue by 24Marques** [xatupal/KeeTheme#6]
Hi, first of all great plugin for Keepass!
I just wanted to inform I found what I think is a bug which is, when you rearrange columns from the list view, every column works fine except the first one (Title). If, for example, I move the UserName col to first position on the table, both UserName col and Title col occupy the same space and are on top of each other, making it impossible to use it this way. Other than that, everything looks nice.
Thank you.

Example:
![image](https://user-images.githubusercontent.com/52248535/60188223-da4a6a80-9826-11e9-82f6-30a1e7fd4150.png)
![image](https://user-images.githubusercontent.com/52248535/60188197-ce5ea880-9826-11e9-8b18-20e6a4350ed5.png)

**Comment by xatupal** [comment]
Thanks :) The problem was due to bug in ListView class. Fortunately it was easy to fix.
