### ISSUE TITLE
KeeTheme 0.9.3 is available

### ISSUE THREAD

**Issue by AIVAS001** [xatupal/KeeTheme#66]
KeeTheme 0.9.3 is available. This package needs to be updated to reflect the new KeeTheme version

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Isn't it?
- 7edbd342ea1d7c14a780708519597ea104c17f83

The Chocolatey package isn't yet arrived: https://community.chocolatey.org/packages/keepass-plugin-keetheme#versionhistory

**Comment by xatupal** [comment]
Yeah, thanks for reminding me :)
