### ISSUE TITLE
hard to read: light grey entry on white background colour

### ISSUE THREAD

**Issue by un99known99** [xatupal/KeeTheme#67]
Hiya,
for "entry", then "edit entry", tab "advanced", edit "entry string", "name":
background is white and content is light grey which makes it really hard to read

Could that be fixed as well - thanks in advance :)

BR,
Mike

**Comment by un99known99** [comment]
![grafik](https://user-images.githubusercontent.com/1615207/154239638-0b53f623-cc34-4703-9ee4-99491c743a52.png)

**Comment by xatupal** [comment]
Hi! Sure, but I couldn't reproduce the problem. Do you have any other plugins installed?

![obraz](https://user-images.githubusercontent.com/22529861/154343093-41e69226-e088-4f9f-82f3-5397c6583b84.png)

**Comment by un99known99** [comment]
I do have installed
DataBaseBackup
LockAssist
IOProtocolExt
KeePassRPC
QR Code Generator
and some Cipher Plugins
