### ISSUE TITLE
KeeTheme 0.9.5 does not work with Keepass 2.50

### ISSUE THREAD

**Issue by caricas91** [xatupal/KeeTheme#68]
Hello,

KeeTheme 0.9.5 does not work with Keepass 2.50.

Keep up the good job.

Thank you.

**Comment by AnonymousWP** [comment]
I can confirm. It says it's not compatible:

![image](https://user-images.githubusercontent.com/50231698/155294369-f3c9baa6-782a-4a76-a126-446776ee5e6e.png)

**Comment by BrokenTwin** [comment]
![image](https://user-images.githubusercontent.com/48297737/155311324-45f3354a-30f5-4566-8a56-5823aaba5007.png)
Can confirm as well. My dark theme from the previous version of keetheme is still active, but the buttons are grey text on grey/light grey backgrounds, and the plugin doesn't show up in the plugin list.
I have no other plugins installed, running the application on Windows 10.

**Comment by MattJeanes** [comment]
Same error, with both the DLL and PLGX versions, the previous version v0.9.4 works fine - latest KeePass 2.50 64-bit

**Comment by inthemix94500** [comment]
Hi

KeeTheme 0.9.5 does not work with Keepass 2.50.
![image](https://user-images.githubusercontent.com/20473311/155319377-cbd51fa2-f52e-4caf-9089-908679c6a1cc.png)


 very good job

Bye

**Comment by dstj** [comment]
> Same here, Does anyone have a link to the .09.4 version? Like an idiot I overwrote the .dll file with the .09.5 version.

Check the release page, they're all there: https://github.com/xatupal/KeeTheme/releases

Or use [Chocolatey](https://community.chocolatey.org/packages/keepass-plugin-keetheme): `choco install keepass-plugin-keetheme --version=0.9.4`

**Comment by ragnarlb33** [comment]
Thanks, just found it.  Github is like a maze in a maze.

**Comment by ThePhOeNiX810815** [comment]
same issue, null reference exception

**Comment by xatupal** [comment]
Sorry, silly mistake ;) Fixed.

**Comment by inthemix94500** [comment]
ohh cool is solved very good job 

very thank you is realy good plugin
