### ISSUE TITLE
Flash when Add New Entries under Dark Theme

### ISSUE THREAD

**Issue by chenrylee** [xatupal/KeeTheme#7]
**OS**: Windows 10 ENT 1903, latest version
**App**: KeePass 2.42.1 x64, portable version
**KeeTheme**: Latest version (just downloaded)  
  
When adding new entries, the window flashes after clicking `OK` button.

**Comment by xatupal** [comment]
Thanks for info. Could you provide a video? I can not reproduce this behavior. Are there any other conditions that must be met?

**Comment by chenrylee** [comment]
I recorded a gif (to reduce the file size, I removed some frames): 
https://github.com/chenrylee/ps-repo/blob/master/darktheme_flash.gif 
[![](https://github.com/chenrylee/ps-repo/blob/master/darktheme_flash.gif)](https://github.com/chenrylee/ps-repo/blob/master/darktheme_flash.gif)
(Seems gif animation can't be embedded.)  
It's recorded by [ScreenToGif](https://www.screentogif.com), and you can find the project file [here](https://github.com/chenrylee/ps-repo/blob/master/darktheme_flash.stg).  
In the project, you can find there're 2 white images.

**Comment by xatupal** [comment]
Thanks for the video. Now I know what's going on. For a short period of time all the controls are disabled. Same flashing occurs when the database is saved. To fix it I have to find a way to substitute a color of disabled control. By default Windows makes those controls gray.

**Comment by BradyThe** [comment]
I worked around this problem in my skin by adding a background image to the ListView. A 1x1 transparent pixel is already sufficient to prevent the flashing. Obviously this is not a perfect solution (if it can be called a solution at all), but I am incapable of doing more from my side.

**Comment by xatupal** [comment]
@BradyThe this workaround should not be needed anymore. Furthermore, I have fixed flashing of RichTextBox.
