### ISSUE TITLE
OddRowColor of ListView can't be set after update

### ISSUE THREAD

**Issue by enahonblanco** [xatupal/KeeTheme#70]
Hello,
I updated KeeTheme from v0.9.4 to v0.9.6 and right after the start-up of KeePass (v2.50), the DarkTheme seemed off. Apparently, without me changing anything else, KeeTheme didn't display the correct color set by the DarkTheme.ini for the OddRowColor property. However, besides that everything else is displaying correctly like before the update.

![grafik](https://user-images.githubusercontent.com/62061227/157735849-00f5aed9-d74e-432f-847a-61ceb172f18f.png)

**Comment by 24Marques** [comment]
Same problem here

**Comment by xatupal** [comment]
Thanks for the detailed explanation!
