### ISSUE TITLE
URL Font Color

### ISSUE THREAD

**Issue by madburg** [xatupal/KeeTheme#72]
Hi, great plugin thanks for sharing. Question, is there a way to change the color of the URL font  it blue and is hard to read with a dark background color. Appreciate any suggestions how to accomplish this.

**Comment by xatupal** [comment]
Hi! Thanks! 

- Please download the file: [DarkTheme.ini](https://raw.githubusercontent.com/xatupal/KeeTheme/master/themes/DarkTheme.ini). 
- Rename it to `KeeTheme.ini`
- Copy it to the KeePass Plugins directory (probably C:\Program Files\KeePass Password Safe 2\Plugins\). 
- Edit the KeeTheme.ini file. In the line 16th there is a color of a link: `Link = (110, 179, 248)`.
- Change it to one that suits you the best, for example red `Link = (255, 0, 0)`.
- Save and execute KeePass.
- Enjoy your new color!

**Comment by madburg** [comment]
Hi, thank you for the feedback. I actually did try "Link" value and what I noticed was it would change the color of a typed entry of a URL in say notes but not in the default URL field, that why I opened the ticket. Attaching example for you to review and comment on.

![Example](https://user-images.githubusercontent.com/2113383/163889690-81eaec42-b069-42b5-aa0a-686b874da01a.jpg)
.

**Comment by xatupal** [comment]
Hi! I see, but I'm not familiar with that view. Could you tell me how to open it? I mean, the view with "Fields", "Properties", "All text" tabs.

**Comment by madburg** [comment]
Hi, sure, here you go:

![Example2](https://user-images.githubusercontent.com/2113383/164154817-81202a65-03ee-4193-96f2-7ea70cd088ee.jpg)

**Comment by xatupal** [comment]
My entry view looks different. Do you have any other plugins installed?

**Comment by madburg** [comment]
Hmmm, yeah looks like your right, it is s called "KPEnhancedEntryView" (KPEnhanced entry view for KeePass). If you have time take a look. I like it so much I am always in that view, so totally forgot its a plug-in.

**Comment by xatupal** [comment]
Done. It will be supported in the next version. Enjoy!

**Comment by madburg** [comment]
Sweet! Thank you for taking the time out and looking into this and making the addition.
Question, if i read the change correctly, it will be  via a new palette entry named "HyperlinkStyle" ?

**Comment by xatupal** [comment]
You're welcome! For consistency, it uses the same entry as any other link.

**Comment by madburg** [comment]
Hi, fyi on Windows 10 with Keepass 2.52 (or 2.51.1 tested both),updating your plugin from v0.9.11 to v0.10 this addition/feature is lost?

**Comment by xatupal** [comment]
I can't verify it on Windows 10, but on Windows 11 it works as before:
![obraz](https://user-images.githubusercontent.com/22529861/202553526-082e433d-c263-49b5-8aa4-a957ddff6862.png)
