### ISSUE TITLE
Can we get a darker theme?

### ISSUE THREAD

**Issue by JoshuaVanDaalen** [xatupal/KeeTheme#75]
Just like you see here on the create Issue page.

Title bar is dark, and the background is a lighter black.

If you want me to figure it out an make a PR I will, but only if you ask.

**Comment by xatupal** [comment]
Actually, darker theme already exists. You can download it from here [DarkenKP](https://github.com/BradyThe/DarkenKP).
I like the idea to match Windows 10 dark mode, but I would rather not make a breaking change.
Maybe I could add an option to choose one of several predefined themes. I'll think about it.

**Comment by xatupal** [comment]
Since version 0.10.0 you can select one of two themes: the original and another one which was inspired by Windows 11 dark theme. You can also download even darker theme from the link I mentioned before.

**Comment by JoshuaVanDaalen** [comment]
Looks amazing, works great, I will be reviewing the code changes to see what was done to give us this nice experience.
