### ISSUE TITLE
"generate password" menu colors problem - dark on dark

### ISSUE THREAD

**Issue by SilenyKrecek** [xatupal/KeeTheme#77]
Hello, 
when using "generate a password" button in an entry, a menu is shown which has black text on a dark background, so it is almost unreadable. See attached screenshot. Can it be adjusted, please? The light text would be consistent with other parts in dark mode.

Thanks! (and thanks for your work, Krzystof!)

SilenyKrecek

![keetheme_generate_password_menu](https://user-images.githubusercontent.com/92733766/167403137-2a61f6ae-2189-4330-bd06-4104a705845f.png)

**Comment by xatupal** [comment]
Hello,
it turned out that it was broken after recent changes in KeePass. 
Fortunately, after a little bit of hacking I was able to make it work.

Enjoy SilenyKrecek!
