### ISSUE TITLE
incompatible with KpEnhancedListView

### ISSUE THREAD

**Issue by yamlCase** [xatupal/KeeTheme#8]
Column headers are not changed with KPEnhancedListView plugin:

https://github.com/betonme/kpenhancedlistview

**Comment by xatupal** [comment]
I've checked KPEnhancedListView code ([InlineEditing](https://github.com/betonme/kpenhancedlistview/blob/master/KPEnhancedListview/InlineEditing.cs)) and the bad news are that it forces ListView to use default drawing. KeeTheme needs custom drawing to work properly, so the plugins are incompatible.

Probably they can be made compatible but the changes have to be done in KPEnhancedListView.
