### ISSUE TITLE
Chocolatey version is outdated on 0.9.1.1 although newest verison is 0.9.4

### ISSUE THREAD

**Issue by PalmTamino** [xatupal/KeeTheme#80]
![grafik](https://user-images.githubusercontent.com/36358673/184540040-65d8f25f-ab08-4287-81aa-4640361978a1.png)

**Comment by xatupal** [comment]
Hi! Your current version is 0.9.4 and the newest version is 0.9.11. 
The newest version is also available on Chocolatey (it's not 0.9.1.1, it's 0.9.11).
