### ISSUE TITLE
Keetheme incompatible with Keepass 2.51.1?

### ISSUE THREAD

**Issue by dedivrselmnts** [xatupal/KeeTheme#82]
Hello,
Since updating to KP Theme 9.12 the attached screenshot displays for permitting login. Once logged in and a check for updates performed, the 2nd screenshot conforms all versions are current. Functionality doesn't seem affected.
![KP Theme error](https://user-images.githubusercontent.com/3149486/188491753-897cd71f-97b0-417a-90a6-8a62084eb27d.JPG)
![KP Upd Chk](https://user-images.githubusercontent.com/3149486/188491771-6c85366b-fcf8-432b-8ab4-4cd325b29d11.JPG)

The means for installing the plugin according to KP doc would be appreciated.

**Comment by gusowski1** [comment]
At least in the plgx version of the plugin i doesn't have this error.
Probaly switching to the plgx version will work for you as well.

**Comment by xatupal** [comment]
Hello! I can't reproduce the error. I tested both versions: dll and plgx. It's really weird that the plugin works despite the error. Do you have any other plugin installed?

**Comment by dedivrselmnts** [comment]
Thanks all. @xatupal, yes, I have Advanced Connect and Keepass Quick Unlock. Removing the dll and implementing @gusowski1 suggestion resolved it.
