### ISSUE TITLE
Display of links

### ISSUE THREAD

**Issue by doctorrerumnaturalium** [xatupal/KeeTheme#84]
If links are displayed, they are covered with a kind of shadow (see attached).

![grafik](https://user-images.githubusercontent.com/59892214/191500091-ac9abd0e-6fa0-468e-9f0c-f5616e0c8e7b.png)

**Comment by Darthagnon** [comment]
![KeePass_RHQZCJyuXM](https://user-images.githubusercontent.com/20792748/212782413-9ce8db34-f99e-44ab-a2c8-04b4539e67c9.png)
Been an issue for at least 2 years; affects even custom themes: https://github.com/Darthagnon/keepass-better-dark-theme

**Comment by doctorrerumnaturalium** [comment]
Work's fine, looks pretty good. Thank you!

**Comment by Darthagnon** [comment]
As far as I know, I'm using the default font, but it's all fixed with the new update, so I'm happy. Thank you!
