### ISSUE TITLE
listview hover highlight not respected

### ISSUE THREAD

**Issue by ejwcobra** [xatupal/KeeTheme#85]
I using the DarkenKP theme as recommended in issue #75.  The listview hover highlight color is not respected, or perhaps I'm configuring it in the wrong place?

![listview hover highlight not respected](https://user-images.githubusercontent.com/23238977/195894123-33a6f555-4db0-4929-859a-2a1233307e41.png)

Here is the theme file I'm using:
[theme.zip](https://github.com/xatupal/KeeTheme/files/9788245/theme.zip)

**Comment by xatupal** [comment]
Hi! Unfortunately, it is impossible to change the color of the highlighted line.
The color you've changed is the color of the highlighted group e.g. "Database" in the image:
![obraz](https://user-images.githubusercontent.com/22529861/196003471-27ba318b-c57d-4baa-9f74-bff1d2f543c0.png)

**Comment by xatupal** [comment]
Since there is nothing I can do about it I'm closing the ticket.
