### ISSUE TITLE
Context menu text

### ISSUE THREAD

**Issue by caspadan** [xatupal/KeeTheme#89]
Hello, i really love the work you do on this plugin, and just want you to know it is very much appreciated.
I notice some darker text in some of the context menus. When right-clicking in the main window on the column header (to configure columns), and the context menu in the entry view - i am using the KPEnhancedEntryView plugin, however it occurs in the context menu even without KPEnhancedEntryView.
![kT](https://user-images.githubusercontent.com/61324156/214014797-52a8c8e9-c670-47d5-aa33-a714f492c2db.jpg)

**Comment by xatupal** [comment]
Hello, I'm glad that you love it. I've found the cause of the problem with KPEnhancedEntryView but I will have to investigate more to also fix "Configure columns".

**Comment by caspadan** [comment]
No worries. I don't mind the plugin as is, I just wanted to let you know.
By the way, even without KPEnhancedEntryView plugin, the context menu in default entry view is also dark. I made sure to test it without the plugin.  Thank you. And do take your time - your life is more important.
