### ISSUE TITLE
Configure Columns validation boxes missing

### ISSUE THREAD

**Issue by 24Marques** [xatupal/KeeTheme#9]
Hello again, found a new small bug related to columns.

On View > "Configure Columns" menu, the validation boxes are missing making it impossible to choose the columns to show in the main window.
Examples:
With dark theme activated:
![image](https://user-images.githubusercontent.com/52248535/60451939-3b0de480-9c25-11e9-9bd1-21ba8cd69801.png)
With dark theme deactivated:
![image](https://user-images.githubusercontent.com/52248535/60451941-3d703e80-9c25-11e9-834b-8df8823ec4c9.png)

**Comment by xatupal** [comment]
Thanks for info. Fixed.
