### ISSUE TITLE
Options tab missing

### ISSUE THREAD

**Issue by scarlion1** [xatupal/KeeTheme#93]
How come I can't see this tab in my options?
https://github.com/xatupal/KeeTheme/blob/master/docs/KeePassDarkThemeCustomOptions.png
There isn't anything after "Advanced" in my KeePass, which is v2.54 now.  Don't have any arrow buttons either as if there were more tabs to the right.

The plugin is otherwise loaded and active and Ctrl-T toggles it, can see "Tools > Dark theme" menu item as well...
Thanks

**Comment by xatupal** [comment]
Hi! I've checked KeeTheme in KeePass v2.54 and I can't reproduce the problem.
Do you have any other plugins installed?

**Comment by scarlion1** [comment]
Just SftpSync

**Comment by xatupal** [comment]
Still no luck. Does it work in the previous KeePass version?

**Comment by scarlion1** [comment]
Well, now it's become more of an issue because Ctrl-T is also the shortcut key to copy an OTP code, which I'd like to be able to do.&nbsp;&nbsp;However, Ctrl-T toggles the dark theme on/off.&nbsp;&nbsp;Any idea how I could change the shortcut key?&nbsp;&nbsp;Thanks

**Comment by scarlion1** [comment]
Usually the options are stored in a config file somewhere or registry key, right?  Is that the case here?  Then I could just change the config file or registry key directly...

**Comment by xatupal** [comment]
The options are stored in KeePass.config.xml file. Insert/modify the following lines if you want to change your hotkey to e.g. Ctrl+G:
```
<Custom>
  <Item>
    <Key>KeeTheme.HotKey</Key>
    <Value>G, Control</Value>
  </Item>
</Custom>
```

**Comment by scarlion1** [comment]
Awesome!  That worked like a charm!  and Ctrl-T now copies the OTP code.  Thanks!!
