### ISSUE TITLE
KeeTheme causing a .net failure

### ISSUE THREAD

**Issue by alex-dacosta** [xatupal/KeeTheme#96]
Good morning
From time to time KeePass 2.54 fails through a .net error.  As a consequence it also freezes.
I have 3 plugins installed:
* IOProtocolExt 1.16.0
* KeePassRPC 1.15.1
* KeeTheme 0.10.2

Looking at the log file, the last one (KeeTheme), seems to be the origin of the failure.
Regards
[2023-09-18 KeePass 2.54 .net failure.txt](https://github.com/xatupal/KeeTheme/files/12645324/2023-09-18.KeePass.2.54.net.failure.txt)

**Comment by xatupal** [comment]
Hey! Thanks for info. I'll fix it.
