### ISSUE TITLE
Auto-type syntax highlighting missing

### ISSUE THREAD

**Issue by santo998** [xatupal/KeeTheme#97]
Syntax highlighting is missing. It's text is displayed in grey.

It should be green or red (if an error exist).

Can it be fixed?

Thank you in advance

**Comment by xatupal** [comment]
Hey! Can you give me more details or share a screenshot?

**Comment by santo998** [comment]
![Dark theme](https://github.com/xatupal/KeeTheme/assets/15607273/ebb9266f-5954-41ce-92f6-b92d0fb0d2cf)
![Standard theme](https://github.com/xatupal/KeeTheme/assets/15607273/bf4fc189-42b0-4aee-8491-b9a830cda716)

Sure, I attached an standard theme and a dark theme screenshot.

There you can see that in standard theme the auto-type syntax errors get highlighted, but in dark theme they don't.

**Comment by xatupal** [comment]
Ok, thanks for info. I'll see if I can do something about it.

**Comment by xatupal** [comment]
Fixed, but I think I will keep these colors for now. They look quite good:
![obraz](https://github.com/xatupal/KeeTheme/assets/22529861/0d385112-a688-429c-ba0b-0c942aaef38d)
