### ISSUE TITLE
Exception when shutdown pc

### ISSUE THREAD

**Issue by santo998** [xatupal/KeeTheme#98]
I have KeePass 2.55 (last version) and last version of KeeTheme.

When I shutdown my pc with KeeTheme enabled (dark theme), I got an exception.

I had two opened databases (master and child) and the child database had unsaved changes.

Here is an screenshot of the exception:

![imagen](https://github.com/xatupal/KeeTheme/assets/15607273/84d92457-9f22-427e-a4ae-c40ce6f4e7ec)

And here is it's text (I use spanish translation of KeePass):

Consulte el final de este mensaje para obtener más detalles sobre cómo invocar a la depuración 
Just-In-Time (JIT) en lugar de a este cuadro de diálogo.

************** Texto de la excepción **************
System.ComponentModel.Win32Exception (0x80004005): The handle is invalid
   en System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize, CopyPixelOperation copyPixelOperation)
   en System.Drawing.Graphics.CopyFromScreen(Point upperLeftSource, Point upperLeftDestination, Size blockRegionSize)
   en KeeTheme.Decorators.ControlSnapshot.CopyFromScreen(Control control)
   en KeeTheme.Decorators.ControlSnapshot.TryCopyFromScreen(Control control)
   en KeeTheme.Decorators.ControlSnapshot.Make(Control control)
   en KeeTheme.Decorators.ListViewDecorator.ListViewParentEnabledChanged(Object sender, EventArgs e)
   en System.Windows.Forms.Control.OnEnabledChanged(EventArgs e)
   en System.Windows.Forms.Control.OnParentEnabledChanged(EventArgs e)
   en System.Windows.Forms.Control.OnEnabledChanged(EventArgs e)
   en System.Windows.Forms.Control.OnParentEnabledChanged(EventArgs e)
   en System.Windows.Forms.Control.OnEnabledChanged(EventArgs e)
   en System.Windows.Forms.Control.OnParentEnabledChanged(EventArgs e)
   en System.Windows.Forms.Control.OnEnabledChanged(EventArgs e)
   en System.Windows.Forms.Control.OnParentEnabledChanged(EventArgs e)
   en System.Windows.Forms.Control.OnEnabledChanged(EventArgs e)
   en System.Windows.Forms.Form.OnEnabledChanged(EventArgs e)
   en System.Windows.Forms.Control.set_Enabled(Boolean value)
   en KeePass.Forms.MainForm.UIBlockInteraction(Boolean bBlock)
   en KeePass.Forms.MainForm.SaveDatabase(PwDatabase pdToSave, Object sender)
   en KeePass.Forms.MainForm.CloseDocument(PwDocument dsToClose, Boolean bLocking, Boolean bExiting, Boolean bEcas, Boolean bUpdateUI)
   en KeePass.Forms.MainForm.CloseAllDocuments(Boolean bExiting)
   en KeePass.Forms.MainForm.OnFormClosing(Object sender, FormClosingEventArgs e)
   en System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   en System.Windows.Forms.Form.WmClose(Message& m)
   en KeePass.Forms.MainForm.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Ensamblados cargados **************
mscorlib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9181.0 built by: NET481REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Versión del ensamblado: 2.55.0.18042
    Versión Win32: 2.55.0.0
    Código base: file:///C:/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
System
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9172.0 built by: NET481REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9181.0 built by: NET481REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9037.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9037.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9181.0 built by: NET481REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9037.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9037.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Accessibility
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9037.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
KeeAutoExec
    Versión del ensamblado: 2.6.0.0
    Versión Win32: 2.6.0.0
    Código base: file:///C:/KeePass%20Password%20Safe%202/Plugins/KeeAutoExec-2.6/KeeAutoExec.dll
----------------------------------------
KeeTheme
    Versión del ensamblado: 0.10.2.0
    Versión Win32: 0.10.2.0
    Código base: file:///C:/KeePass%20Password%20Safe%202/Plugins/KeeTheme-0.10.2/KeeTheme.dll
----------------------------------------
QualityColumn
    Versión del ensamblado: 1.3.0.0
    Versión Win32: 1.3.0.0
    Código base: file:///C:/KeePass%20Password%20Safe%202/Plugins/QualityColumn-1.3/QualityColumn.dll
----------------------------------------
WebAutoType
    Versión del ensamblado: 2.42.0.0
    Versión Win32: 6.9.0.0
    Código base: file:///C:/KeePass%20Password%20Safe%202/Plugins/WebAutoType-v6.9.0/WebAutoType.dll
----------------------------------------
SourceForgeUpdateChecker
    Versión del ensamblado: 2.22.0.0
    Versión Win32: 0.4.0.0
    Código base: file:///C:/Users/santo/AppData/Local/KeePass/PluginCache/3QWTLSuWPqGmkpoRMnc8/SourceForgeUpdateChecker.dll
----------------------------------------
System.Security
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9037.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
System.Data.SqlXml
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9037.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll
----------------------------------------
KeePass.XmlSerializers
    Versión del ensamblado: 2.55.0.18042
    Versión Win32: 2.55.0.18042
    Código base: file:///C:/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL
----------------------------------------
System.Web
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9191.0 built by: NET481REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
mscorlib.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9037.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_es_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Depuración JIT **************
Para habilitar la depuración Just In Time (JIT), el archivo de configuración de esta
aplicación o equipo (machine.config) debe tener el
valor jitDebugging establecido en la sección system.windows.forms.
La aplicación también se debe compilar con la depuración
habilitada

Por ejemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Cuando esté habilitada la depuración JIT, cualquier excepción no controlada
se enviará al depurador JIT registrado en el equipo
en lugar de controlarlo mediante el cuadro de diálogo.

**Comment by xatupal** [comment]
Hey! Thanks for info. I'll fix it.
